---
driver:
  name: vagrant
  synced_folders:
  - ["./", "/cookbook"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31

platforms:
  - name: bento/centos-6.7

suites:
  - name: primary1
    provisioner:
      client_rb:
        environment: prod_tools
    driver:
      vm_hostname: nag1.test.manasg.com
      customize:
        memory: 2048
        cpus: 2
      network:
      - ["forwarded_port", {guest: 80, host: 30080}]
    run_list:
      - 'mg_nagios'
    attributes:
      nagios:
        default_service:
          check_interval: 15
      target_servers:
        candidate1:
          fqdn: prodsrv1.test.manasg.com
          ipaddress: 172.28.128.3
        candidate2:
          fqdn: devsrv1.test.manasg.com
          ipaddress: 172.28.128.4

  - name: candidate1
    driver:
      vm_hostname: prodsrv1.test.manasg.com
      customize:
        memory: 512
        cpus: 1
      network:
      - ["private_network", { ip: "172.28.128.3" } ]
    run_list:
      - 'mg_nagios::sample_common'

  - name: candidate2
    driver:
      vm_hostname: devsrv1.test.manasg.com
      customize:
        memory: 512
        cpus: 1
      network:
      - ["private_network", { ip: "172.28.128.4" } ]
    run_list:
      - 'mg_nagios::sample_common'
